const ORACLE_NATIVE_METRIC_NAMES = [
  'User Calls Per Sec',
  'Executions Per Sec',
  'Database Time Per Sec',
  'CPU Usage Per Sec',
  'Logical Reads Per Sec',
  'Physical Reads Per Sec',
  'Physical Writes Per Sec',
] as const;

const metricNamesSql = ORACLE_NATIVE_METRIC_NAMES.map((name) => `'${name}'`).join(', ');

export const ORACLE_DASHBOARD_CONTEXT_SQL = `
SELECT
  SYS_CONTEXT('USERENV', 'DB_NAME') AS DATABASE_NAME,
  SYS_CONTEXT('USERENV', 'CON_NAME') AS CONTAINER_NAME,
  TO_NUMBER(SYS_CONTEXT('USERENV', 'CON_ID')) AS CONTAINER_ID,
  SYS_CONTEXT('USERENV', 'INSTANCE_NAME') AS INSTANCE_NAME,
  SYS_CONTEXT('USERENV', 'SID') AS OBSERVER_SID,
  (SELECT MAX(VERSION) FROM PRODUCT_COMPONENT_VERSION) AS SERVER_VERSION
FROM DUAL`;

export const ORACLE_DASHBOARD_INSTANCE_SYSMETRIC_SQL = `
SELECT GROUP_ID, METRIC_NAME, VALUE, METRIC_UNIT, INTSIZE_CSEC, BEGIN_TIME, END_TIME, CON_ID
FROM V$SYSMETRIC
WHERE METRIC_NAME IN (${metricNamesSql})`;

export const ORACLE_DASHBOARD_PDB_SYSMETRIC_SQL = `
SELECT GROUP_ID, METRIC_NAME, VALUE, METRIC_UNIT, INTSIZE_CSEC, BEGIN_TIME, END_TIME, CON_ID
FROM V$CON_SYSMETRIC
WHERE METRIC_NAME IN (${metricNamesSql})
  AND CON_ID = TO_NUMBER(SYS_CONTEXT('USERENV', 'CON_ID'))`;

export const ORACLE_DASHBOARD_SESSIONS_SQL = `
SELECT
  SYSTIMESTAMP AS OBSERVED_AT,
  STATUS,
  NVL(WAIT_CLASS, 'CPU') AS WAIT_CLASS,
  COUNT(*) AS SESSION_COUNT,
  CON_ID
FROM V$SESSION
WHERE TYPE = 'USER'
  AND SID <> TO_NUMBER(SYS_CONTEXT('USERENV', 'SID'))
  AND CON_ID = TO_NUMBER(SYS_CONTEXT('USERENV', 'CON_ID'))
GROUP BY STATUS, NVL(WAIT_CLASS, 'CPU'), CON_ID`;

export const ORACLE_DASHBOARD_RESOURCE_LIMIT_SQL = `
SELECT RESOURCE_NAME, CURRENT_UTILIZATION, MAX_UTILIZATION, LIMIT_VALUE, CON_ID
FROM V$RESOURCE_LIMIT
WHERE RESOURCE_NAME IN ('sessions', 'processes')`;

export const ORACLE_DASHBOARD_SYSTEM_EVENT_SQL = `
SELECT WAIT_CLASS, SUM(TIME_WAITED_MICRO) AS TIME_WAITED_MICRO, CON_ID
FROM V$SYSTEM_EVENT
WHERE WAIT_CLASS <> 'Idle'
GROUP BY WAIT_CLASS, CON_ID`;

export const ORACLE_DASHBOARD_SYSSTAT_SQL = `
SELECT s.NAME, s.VALUE, s.CON_ID, i.STARTUP_TIME
FROM V$SYSSTAT s
CROSS JOIN V$INSTANCE i
WHERE s.NAME IN ('user calls', 'execute count', 'session logical reads', 'physical reads', 'physical writes')
  AND s.CON_ID IN (0, TO_NUMBER(SYS_CONTEXT('USERENV', 'CON_ID')))`;

export const ORACLE_DASHBOARD_NATIVE_METRIC_NAMES = ORACLE_NATIVE_METRIC_NAMES;
