version: '3'

services:
  redis:
    image: redis:5.0
    container_name: redis_container
    command: redis-server --requirepass testpass
    ports:
      - '6000:6379'

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs
    container_name: mysql_container
    ports:
      - 6001:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  mysql5:
    image: mysql:5.7.27
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4
    container_name: mysql5_container
    ports:
      - 6011:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  postgres:
    image: postgres:14
    container_name: postgres_container
    ports:
      - 6002:5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql_container
    ports:
      - '6433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass123zxcv!
      - MSSQL_PID=Express
      - MSSQL_LCID=1041 # Japanese
      - MSSQL_COLLATION=Japanese_CI_AS
      - TZ="Asia/Tokyo"

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_container
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpass
    command: server --console-address ":9001" /data
    ports:
      - 6003:9000
      - 6004:9001

  localstack:
    image: localstack/localstack
    ports:
      - 6005:4566 # all services
      - 6006:8080 # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICES=s3,sqs,ses,cloudwatch,cloudformation,logs,lambda,dynamodb,stepfunctions,iam
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
      #      - LAMBDA_DOCKER_NETWORK=host
      - DYNAMODB_SHARE_DB=1

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - '6100:8080'
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev

volumes:
  localstack-data:
    driver: 'local'
